langsorder:
- id: de
- id: id
- id: en
- id: es
- id: fr
- id: it
- id: nl
- id: pl
- id: ru
- id: tr
- id: bg
- id: zh_CN
- id: zh_TW
- id: ar
- id: fa

langs:
  ar: ألعربية
  bg: български
  de: Deutsch
  en: English
  es: Español
  fa: فارسی
  fr: Français
  id: Bahasa Indonesia‬
  it: Italiano
  nl: Nederlands
  pl: Polski
  ru: Русский
  tr: Türkçe
  zh_CN: ‪简体中文‬
  zh_TW: ‪繁體中文‬

redirects:
  /news: /en/version-history
  /clients: /en/choose-your-wallet
  /about: /en/faq
  /de/ueber: /de/faq
  /en/about: /en/faq
  /es/acerca-de: /es/faq
  /fr/a-propos: /fr/faq
  /ru/описание: /ru/faq
  /ar/بت-كوين-للهواة: /ar/innovation
  /de/bitcoin-fuer-enthusiasten: /de/innovation
  /en/bitcoin-for-enthusiasts: /en/innovation
  /es/bitcoin-para-entusiastas: /es/innovacion
  /fa/بیت-کوین-برای-علاقه-مندان: /fa/innovation
  /fr/bitcoin-pour-passionnes: /fr/innovation
  /it/bitcoin-per-appassionati: /it/innovazione
  /nl/bitcoin-voor-liefhebbers: /nl/innovatie
  /pl/bitcoin-dla-entuzjastow: /pl/innowacje
  /ru/биткоин-энтузиастам: /ru/innovation
  /en/bitcoin-for-press: /en/press

aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
